import { BaseLevel } from "@/types/data/Level";
import { BaseSubject } from "@/types/data/Subject";
import { v4 as uuidv4 } from "uuid";
import { subjects } from "./subjects";
const levelSubjectsMap: { [key: string]: string[] } = {
  "Primary 1": [
    "English Language",
    "Mother Tongue Language (Chinese/Malay/Tamil)",
    "Mathematics",
    "Science",
    "Social Studies",
    "Character and Citizenship Education (CCE)",
    "Physical Education (PE)",
    "Music",
    "Art",
  ],
  "Primary 2": [
    "English Language",
    "Mother Tongue Language (Chinese/Malay/Tamil)",
    "Mathematics",
    "Science",
    "Social Studies",
    "Character and Citizenship Education (CCE)",
    "Physical Education (PE)",
    "Music",
    "Art",
  ],
  "Primary 3": [
    "English Language",
    "Mother Tongue Language (Chinese/Malay/Tamil)",
    "Mathematics",
    "Science",
    "Social Studies",
    "Character and Citizenship Education (CCE)",
    "Physical Education (PE)",
    "Art",
    "Music",
  ],
  "Primary 4": [
    "English Language",
    "Mother Tongue Language (Chinese/Malay/Tamil)",
    "Mathematics",
    "Science",
    "Social Studies",
    "Character and Citizenship Education (CCE)",
    "Physical Education (PE)",
    "Art",
  ],
  "Primary 5": [
    "English Language",
    "Mother Tongue Language (Chinese/Malay/Tamil)",
    "Mathematics",
    "Science",
    "Social Studies",
    "Character and Citizenship Education (CCE)",
    "Physical Education (PE)",
    "Art",
    "Music",
  ],
  "Primary 6": [
    "English Language",
    "Mother Tongue Language (Chinese/Malay/Tamil)",
    "Mathematics",
    "Science",
    "Social Studies",
    "Character and Citizenship Education (CCE)",
    "Physical Education (PE)",
    "Music",
  ],
  "Sec 1": [
    "English Language",
    "Mother Tongue Language (Chinese/Malay/Tamil)",
    "Mathematics",
    "Science",
    "Geography",
    "History",
    "Literature",
    "Art",
    "Music",
    "Physical Education (PE)",
    "Character and Citizenship Education (CCE)",
  ],
  "Sec 2": [
    "English Language",
    "Mother Tongue Language (Chinese/Malay/Tamil)",
    "Mathematics",
    "Science",
    "Geography",
    "History",
    "Literature",
    "Design and Technology",
    "Food and Nutrition",
    "Art",
    "Physical Education (PE)",
  ],
  "Sec 3": [
    "English Language",
    "Mother Tongue Language (Chinese/Malay/Tamil)",
    "Mathematics",
    "Additional Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Geography",
    "History",
    "Literature",
    "Principles of Accounts",
    "Combined Science (Physics/Chemistry)",
    "Combined Science (Chemistry/Biology)",
    "Design and Technology",
    "Art",
    "Physical Education (PE)",
  ],
  "Sec 4": [
    "English Language",
    "Mother Tongue Language (Chinese/Malay/Tamil)",
    "Mathematics",
    "Additional Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Geography",
    "History",
    "Literature",
    "Principles of Accounts",
    "Combined Science (Physics/Chemistry)",
    "Combined Science (Chemistry/Biology)",
    "Design and Technology",
    "Art",
  ],
  "Sec 5": [
    "English Language",
    "Mother Tongue Language (Chinese/Malay/Tamil)",
    "Mathematics",
    "Additional Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Geography",
    "History",
    "Literature",
    "Principles of Accounts",
    "Art",
  ],
  "JC1": [
    "General Paper",
    "H1 Mathematics",
    "H1 Economics",
    "H1 Geography",
    "H1 History",
    "H1 Literature in English",
    "H1 Physics",
    "H1 Chemistry",
    "H1 Biology",
    "H2 Mathematics",
    "H2 Physics",
    "H2 Chemistry",
    "H2 Biology",
    "H2 Economics",
    "H2 Geography",
    "H2 History",
    "H2 Literature in English",
    "H2 Art",
    "Project Work",
    "H2 Computing",
  ],
  "JC2": [
    "General Paper",
    "H1 Mathematics",
    "H1 Economics",
    "H1 Geography",
    "H1 History",
    "H1 Literature in English",
    "H1 Physics",
    "H1 Chemistry",
    "H1 Biology",
    "H2 Mathematics",
    "H2 Physics",
    "H2 Chemistry",
    "H2 Biology",
    "H2 Economics",
    "H2 Geography",
    "H2 History",
    "H2 Literature in English",
    "H2 Art",
    "Project Work",
    "H2 Computing",
    "H2 Knowledge and Inquiry",
  ],
  "JC3": [
    "General Paper",
    "H3 Mathematics",
    "H3 Physics",
    "H3 Chemistry",
    "H3 Biology",
    "H3 Economics",
    "H3 Geography",
    "H3 History",
    "H3 Literature in English",
    "H2 Knowledge and Inquiry",
  ],
};

const levelsNames = [
  "Primary 1",
  "Primary 2",
  "Primary 3",
  "Primary 4",
  "Primary 5",
  "Primary 6",
  "Sec 1",
  "Sec 2",
  "Sec 3",
  "Sec 4",
  "Sec 5",
  "JC1",
  "JC2",
  "JC3",
];

export type BaseLevelWithSubjects = BaseLevel & { subjects: BaseSubject[] };
export const levels: BaseLevelWithSubjects[] = levelsNames.map((lvl) => {
  let relevantSubjects = subjects.filter((sub) =>
    levelSubjectsMap[lvl].includes(sub.name),
  );

  return {
    id: uuidv4(),
    name: lvl,
    subjects: relevantSubjects,
    // courses: [...Array(randomNumber(10))].map(() => newCourse()),
    // students: [...Array(randomNumber(10))].map(() => newStudent()),
    // educators: [...Array(randomNumber(10))].map(() => newEducator()),
  };
});
