import { BaseSubject } from "@/types/data/Subject";
import { v4 as uuidv4 } from "uuid";

export const subjects: BaseSubject[] = [
  { id: uuidv4(), name: "English Language" },
  { id: uuidv4(), name: "Mother Tongue Language (Chinese/Malay/Tamil)" },
  { id: uuidv4(), name: "Mathematics" },
  { id: uuidv4(), name: "Science" },
  { id: uuidv4(), name: "Social Studies" },
  { id: uuidv4(), name: "Character and Citizenship Education (CCE)" },
  { id: uuidv4(), name: "Physical Education (PE)" },
  { id: uuidv4(), name: "Music" },
  { id: uuidv4(), name: "Art" },
  { id: uuidv4(), name: "Higher Mother Tongue Language" },
  { id: uuidv4(), name: "Foundation Mother Tongue Language" },
  { id: uuidv4(), name: "Additional Mathematics" },
  { id: uuidv4(), name: "Physics" },
  { id: uuidv4(), name: "Chemistry" },
  { id: uuidv4(), name: "Biology" },
  { id: uuidv4(), name: "History" },
  { id: uuidv4(), name: "Geography" },
  { id: uuidv4(), name: "Literature" },
  { id: uuidv4(), name: "Design and Technology" },
  { id: uuidv4(), name: "Food and Consumer Education" },
  { id: uuidv4(), name: "Principles of Accounts" },
  { id: uuidv4(), name: "Computing" },
  { id: uuidv4(), name: "Drama" },
  { id: uuidv4(), name: "Combined Science (Physics/Chemistry)" },
  { id: uuidv4(), name: "Combined Science (Chemistry/Biology)" },
  { id: uuidv4(), name: "Combined Humanities" },
  { id: uuidv4(), name: "Electronics" },
  { id: uuidv4(), name: "Exercise and Sports Science" },
  { id: uuidv4(), name: "Food and Nutrition" },
  { id: uuidv4(), name: "Higher Art" },
  { id: uuidv4(), name: "Higher Music" },
  { id: uuidv4(), name: "General Paper" },
  { id: uuidv4(), name: "Project Work" },
  { id: uuidv4(), name: "H1 Mathematics" },
  { id: uuidv4(), name: "H1 Economics" },
  { id: uuidv4(), name: "H1 Geography" },
  { id: uuidv4(), name: "H1 History" },
  { id: uuidv4(), name: "H1 Literature in English" },
  { id: uuidv4(), name: "H1 Physics" },
  { id: uuidv4(), name: "H1 Chemistry" },
  { id: uuidv4(), name: "H1 Biology" },
  { id: uuidv4(), name: "H2 Mathematics" },
  { id: uuidv4(), name: "H2 Further Mathematics" },
  { id: uuidv4(), name: "H2 Physics" },
  { id: uuidv4(), name: "H2 Chemistry" },
  { id: uuidv4(), name: "H2 Biology" },
  { id: uuidv4(), name: "H2 Economics" },
  { id: uuidv4(), name: "H2 Geography" },
  { id: uuidv4(), name: "H2 History" },
  { id: uuidv4(), name: "H2 Literature in English" },
  { id: uuidv4(), name: "H2 Art" },
  { id: uuidv4(), name: "H2 Chinese Language and Literature" },
  { id: uuidv4(), name: "H2 Translation (Chinese)" },
  { id: uuidv4(), name: "H2 Computing" },
  { id: uuidv4(), name: "H2 Knowledge and Inquiry" },
  { id: uuidv4(), name: "H3 Mathematics" },
  { id: uuidv4(), name: "H3 Physics" },
  { id: uuidv4(), name: "H3 Chemistry" },
  { id: uuidv4(), name: "H3 Biology" },
  { id: uuidv4(), name: "H3 Economics" },
  { id: uuidv4(), name: "H3 Geography" },
  { id: uuidv4(), name: "H3 History" },
];
